### PR TITLE
Update link to Jon's twitter handle

### PR DESCRIPTION
**Pull request by jonnyl**
My twitter handle was updated somewhat recently, just want to update the README to point to the correct/active one.

### CODE REVIEW

**Comment by jonnyl** [comment]
Hey @kaelig Any idea how to get that check above to re-run?

**Comment by kaelig** [comment]
Hey! It looks like you need to link your GitHub account to your w3c account first, can you try that?

**Comment by jonnyl** [comment]
@kaelig I did, but not until after I submitted this PR and that check failed.   Is there a way to re-run, or should i kill this and submit a new one?

**Comment by kaelig** [comment]
Thank you, I revalidated and it worked!

**Comment by jonnyl** [comment]
Thanks for merging, much appreciated!

**Pull request merged**
