### PR TITLE
Add .whitesource configuration file

### PR DESCRIPTION
**Pull request by SynovialWheat9011**
La vie en communauté.

### CODE REVIEW

**Comment by SynovialWheat9011** [comment]
Vie en communauté.

**Comment by jina** [comment]
What is this?

**Comment by frebro** [comment]
Spam? Looks like this user makes lots of random PRs on various projects, all of which get closed.

**Comment by jina** [comment]
> Spam? Looks like this user makes lots of random PRs on various projects, all of which get closed.

thanks. closed it.

**Pull request closed without merging**
