### PR TITLE
Add Herman + Accoutrement to represented projects

### PR DESCRIPTION
**Pull request by mirisuzanne**
I could potentially add Sass to the list as well, but I'd want to confirm that with the rest of the core team first…

### CODE REVIEW

**Comment by dontcallmedom** [comment]
Marked as non substantive for IPR from ash-nazg.

**Comment by mirisuzanne** [comment]
I have joined the community group, and signed the agreement - is there something else I need to do in order for it to validate me?

**Comment by dontcallmedom** [comment]
@mirisuzanne now that your github account has been linked with your w3c account, your future pull requests should be automatically validated - if not, let me know :)

**Comment by mirisuzanne** [comment]
yep, found it right after I asked :p thanks!

**Pull request merged**
